#!/bin/bash

echo "💰 Testing Portfolio Zero Initial Value..."
echo ""
echo "✅ Changes deployed:"
echo "   - HTML default value changed from \$10,000 to \$0"
echo "   - P&L format fixed: +\$0 instead of +0"
echo "   - Trade Amount initialized immediately with \$0"
echo "   - Portfolio updates after 2 seconds with real blockchain data"
echo ""
echo "🔍 How to Test:"
echo ""
echo "1️⃣  Open in INCOGNITO mode (important!):"
echo "   http://152.42.199.50/"
echo ""
echo "2️⃣  Check Portfolio Overview (top left):"
echo "   - Total Value: Should show \$0 immediately"
echo "   - P&L: Should show +\$0"
echo "   - Win Rate: Should show 0%"
echo "   - Total Trades: Should show 0"
echo ""
echo "3️⃣  Check Trade Amount (bottom):"
echo "   - Should show: 25% (\$0)"
echo "   - NOT: 25% (\$2,500)"
echo ""
echo "4️⃣  After 2 seconds:"
echo "   - Values update from blockchain"
echo "   - If no wallet: stays at \$0"
echo "   - If wallet exists: shows real balance"
echo ""
echo "5️⃣  Create wallet and claim faucet:"
echo "   - Total Value: \$0 → \$150"
echo "   - Trade Amount: \$0 → \$37.50 (25% of \$150)"
echo ""
echo "🎯 Expected Behavior:"
echo "   ✅ Initial load: All values show \$0"
echo "   ✅ No flash of \$10,000"
echo "   ✅ Trade amount syncs with portfolio"
echo "   ✅ After faucet: \$150 total, \$37.50 trade amount"
echo ""
echo "📍 Test URL: http://152.42.199.50/"
echo ""
echo "💡 Use Cmd+Shift+R (hard refresh) or incognito mode!"
