#!/bin/bash

echo "🧪 Testing Signal Persistence Feature"
echo "======================================"
echo ""
echo "📋 Test Checklist:"
echo ""
echo "Test 1: Generate Signal with Coin Badge"
echo "  1. Open http://152.42.199.50"
echo "  2. Connect wallet"
echo "  3. Select ETH"
echo "  4. Click 'Generate Signal'"
echo "  5. ✅ Verify signal shows 'HOLD ETH' with badge"
echo "  6. ✅ Verify Risk Management section appears"
echo ""
echo "Test 2: Signal Persistence Across Coin Changes"
echo "  1. With ETH signal active"
echo "  2. Click BTC button"
echo "  3. ✅ Verify ETH signal STILL shows with 'ETH' badge"
echo "  4. ✅ Verify Risk Management section STILL visible"
echo "  5. ✅ Verify Execute button STILL active"
echo ""
echo "Test 3: Execute Trade with Persistent Signal"
echo "  1. With ETH signal active"
echo "  2. Switch to BTC (signal persists)"
echo "  3. Click 'Execute AI Trade'"
echo "  4. ✅ Verify trade executes for ETH (not BTC)"
echo "  5. ✅ Verify signal cleared after execution"
echo ""
echo "Test 4: Generate New Signal Replaces Old"
echo "  1. Generate signal for ETH"
echo "  2. Switch to BTC"
echo "  3. Generate signal for BTC"
echo "  4. ✅ Verify ETH signal replaced with BTC signal"
echo "  5. ✅ Verify badge shows 'BTC'"
echo ""
echo "Test 5: Signal Expiry (15 minutes)"
echo "  1. Generate signal"
echo "  2. Wait 15 minutes (or modify SIGNAL_EXPIRY_MS for testing)"
echo "  3. Switch coin"
echo "  4. ✅ Verify signal auto-cleared"
echo "  5. ✅ Verify Risk Management hidden"
echo ""
echo "🔍 Browser Console Checks:"
echo "  - Look for: '✅ Active signal saved for ETH'"
echo "  - Look for: '📊 Active signal exists for: ETH'"
echo "  - Look for: '✅ Active signal displayed'"
echo ""
echo "🐛 Debugging:"
echo "  - Open browser console (F12)"
echo "  - Check for errors"
echo "  - Run: signalPersistence.getActiveSignal()"
echo "  - Should return signal object or null"
echo ""
echo "📊 Expected Behavior:"
echo "  ✅ Signal persists across coin changes"
echo "  ✅ Coin badge shows which coin signal is for"
echo "  ✅ Risk Management stays visible"
echo "  ✅ Execute button stays active"
echo "  ✅ Trade executes for signal coin, not selected coin"
echo ""
echo "🎯 Success Criteria:"
echo "  All 5 tests pass ✅"
echo ""
