#!/bin/bash

echo "🧪 Testing Wallet Management Features"
echo "======================================"
echo ""
echo "✅ Deployed to: http://152.42.199.50"
echo ""
echo "📋 Test Checklist:"
echo ""
echo "1. Create New Wallet"
echo "   - Click 'Connect Wallet' button"
echo "   - Click 'Create New Wallet'"
echo "   - Wait for wallet creation"
echo "   - ✅ Mnemonic modal should appear automatically"
echo ""
echo "2. Mnemonic Backup Modal"
echo "   - ✅ Should show 12 words in a grid"
echo "   - ✅ Click 'Copy to Clipboard' - should copy mnemonic"
echo "   - ✅ Check 'I have written down my recovery phrase'"
echo "   - ✅ 'Continue' button should become enabled"
echo "   - ✅ Click 'Continue' to close modal"
echo ""
echo "3. Export Wallet"
echo "   - Click wallet button (shows chain ID)"
echo "   - Click '📦 Export Wallet' button"
echo "   - ✅ Export modal should appear"
echo "   - Enter password (min 8 characters)"
echo "   - Confirm password"
echo "   - Click 'Export Wallet'"
echo "   - ✅ Should download .json backup file"
echo ""
echo "4. Import Wallet"
echo "   - Disconnect wallet first"
echo "   - Click 'Connect Wallet'"
echo "   - Click '📥 Import Wallet' button"
echo "   - ✅ Import modal should appear"
echo "   - Select backup .json file"
echo "   - Enter backup password"
echo "   - Click 'Import Wallet'"
echo "   - ✅ Should restore wallet and reload page"
echo "   - ✅ Wallet should be connected with same Chain ID"
echo ""
echo "5. Verify Wallet Persistence"
echo "   - After import, check Chain ID matches original"
echo "   - Check Owner address matches"
echo "   - Check balance is restored"
echo ""
echo "======================================"
echo "🌐 Open: http://152.42.199.50"
echo "💡 Use Cmd+Shift+R (Mac) or Ctrl+Shift+R (Windows) for hard refresh"
echo ""
