#!/bin/bash

echo "🧪 Testing Risk Management Fix"
echo "================================"
echo ""
echo "📋 Test Steps:"
echo "1. Open http://152.42.199.50 in INCOGNITO mode"
echo "2. Connect wallet (or use existing)"
echo "3. Select BTC coin"
echo "4. Click 'Generate Signal'"
echo "5. Check Risk Management section appears"
echo "6. Verify TP/SL values are populated automatically"
echo "7. Click 'AI Suggest TP' button"
echo "8. Click 'AI Suggest SL' button"
echo "9. Manually change TP percentage"
echo "10. Manually change SL price"
echo ""
echo "✅ Expected Results:"
echo "   - Risk Management section shows after signal generation"
echo "   - TP/SL values auto-populated with AI suggestions"
echo "   - AI Suggest buttons work correctly"
echo "   - Manual input updates work (price ↔ percentage sync)"
echo "   - Profit/Loss amounts display correctly"
echo "   - Risk/Reward ratio shows (e.g., 'R:R 1.67:1')"
echo ""
echo "🐛 Previous Issue:"
echo "   - AI Suggest buttons couldn't read currentSignal.price"
echo "   - Error: 'Cannot read percentage'"
echo ""
echo "🔧 Fix Applied:"
echo "   - Added fallback: currentSignal.price || currentSignal.currentPrice"
echo "   - Added fallback: currentSignal.type || currentSignal.signal"
echo "   - All event handlers now use correct property names"
echo ""
echo "🌐 Opening browser..."
open "http://152.42.199.50"
