#!/bin/bash

echo "🧪 Testing AI Explainer - Real Signal Integration"
echo "=================================================="
echo ""
echo "✅ Deployed to: http://152.42.199.50"
echo "📅 Test Date: $(date '+%Y-%m-%d %H:%M:%S')"
echo ""
echo "🔧 Fix Applied:"
echo "   - AI Explainer now uses saved signals from cooldown manager"
echo "   - Shows 'Using Real Signal' banner when signal exists"
echo "   - Shows 'Mock Analysis' banner when no signal generated yet"
echo "   - Displays signal age (e.g., '3 minutes ago')"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Test Scenario 1: With Generated Signal"
echo ""
echo "1. Open Main Dashboard"
echo "   - Go to: http://152.42.199.50"
echo "   - Hard refresh: Cmd+Shift+R"
echo ""
echo "2. Generate Signal"
echo "   - Connect wallet (if not connected)"
echo "   - Select coin (e.g., BTC)"
echo "   - Click 'Generate Signal'"
echo "   - ✅ Signal should be generated"
echo "   - ✅ Risk Management section appears"
echo "   - ✅ Signal saved with 15-min cooldown"
echo ""
echo "3. Open AI Explainer"
echo "   - Click '🧠 AI Explainer' button"
echo "   - OR go to: http://152.42.199.50/ai-explainer.html?coin=BTC"
echo ""
echo "4. Verify Real Signal Usage ⭐ CRITICAL"
echo "   - ✅ Should show blue banner: '📊 Using Real Signal'"
echo "   - ✅ Banner should show: 'Generated X minutes ago'"
echo "   - ✅ Banner should say: 'Signals update every 15 minutes'"
echo "   - ✅ Signal (BUY/SELL/HOLD) should match main dashboard"
echo "   - ✅ Confidence should match main dashboard"
echo "   - ✅ All indicators should be consistent"
echo ""
echo "5. Check Console Logs"
echo "   - Open Console (F12)"
echo "   - ✅ Should see: '📊 Using saved signal for BTC: {...}'"
echo "   - ✅ Should NOT see: 'No saved signal'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Test Scenario 2: Without Generated Signal"
echo ""
echo "1. Clear Signal Data (Optional)"
echo "   - Open Console (F12)"
echo "   - Type: localStorage.removeItem('signalCooldowns')"
echo "   - Press Enter"
echo ""
echo "2. Open AI Explainer for Different Coin"
echo "   - Go to: http://152.42.199.50/ai-explainer.html?coin=ETH"
echo "   - (Assuming you haven't generated signal for ETH)"
echo ""
echo "3. Verify Mock Analysis ⭐"
echo "   - ✅ Should show orange banner: '⚠️ Mock Analysis'"
echo "   - ✅ Banner should say: 'No signal generated yet for ETH'"
echo "   - ✅ Banner should say: 'Go to main dashboard and generate signal first'"
echo "   - ✅ Analysis shown is mock/demo data"
echo ""
echo "4. Check Console Logs"
echo "   - ✅ Should see: '📊 No saved signal for ETH, using mock analysis'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Test Scenario 3: Signal Cooldown Integration"
echo ""
echo "1. Generate Signal on Main Dashboard"
echo "   - Select BTC"
echo "   - Click 'Generate Signal'"
echo "   - ✅ Signal generated"
echo ""
echo "2. Check AI Explainer Immediately"
echo "   - Click '🧠 AI Explainer'"
echo "   - ✅ Should show: 'Generated Just now'"
echo ""
echo "3. Wait 3 Minutes"
echo "   - Wait for 3 minutes"
echo "   - Refresh AI Explainer page"
echo "   - ✅ Should show: 'Generated 3 minutes ago'"
echo ""
echo "4. Wait 15 Minutes"
echo "   - Wait until 15 minutes pass"
echo "   - Go back to main dashboard"
echo "   - ✅ 'Generate Signal' button should be enabled again"
echo "   - Generate new signal"
echo "   - Check AI Explainer"
echo "   - ✅ Should show: 'Generated Just now' (new signal)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Test Scenario 4: Multiple Coins"
echo ""
echo "1. Generate Signals for Multiple Coins"
echo "   - Main dashboard → Select BTC → Generate Signal"
echo "   - Main dashboard → Select ETH → Generate Signal"
echo "   - Main dashboard → Select SOL → Generate Signal"
echo ""
echo "2. Check AI Explainer for Each Coin"
echo "   - AI Explainer → Click BTC button"
echo "   - ✅ Should show BTC real signal"
echo "   - AI Explainer → Click ETH button"
echo "   - ✅ Should show ETH real signal"
echo "   - AI Explainer → Click SOL button"
echo "   - ✅ Should show SOL real signal"
echo "   - AI Explainer → Click BNB button (if not generated)"
echo "   - ✅ Should show BNB mock analysis"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🐛 Debugging Tips:"
echo ""
echo "1. Check localStorage"
echo "   - Console: localStorage.getItem('signalCooldowns')"
echo "   - Should show JSON with coin signals and timestamps"
echo ""
echo "2. Check Signal Data Structure"
echo "   - Console: JSON.parse(localStorage.getItem('signalCooldowns'))"
echo "   - Should show: { BTC: { timestamp: ..., signal: {...} } }"
echo ""
echo "3. Clear All Signals (for testing)"
echo "   - Console: localStorage.removeItem('signalCooldowns')"
echo "   - Refresh page"
echo ""
echo "4. Check Console Logs"
echo "   - Look for '📊 Using saved signal' or '📊 No saved signal'"
echo "   - Check signal data structure"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Expected Behavior:"
echo ""
echo "BEFORE FIX:"
echo "   - AI Explainer always generated new mock analysis"
echo "   - No connection to main dashboard signals"
echo "   - No cooldown integration"
echo ""
echo "AFTER FIX:"
echo "   - AI Explainer uses real signals from main dashboard"
echo "   - Shows signal age (e.g., '3 minutes ago')"
echo "   - Respects 15-minute cooldown"
echo "   - Clear indication: Real Signal vs Mock Analysis"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🌐 Test URLs:"
echo "   Main Dashboard: http://152.42.199.50"
echo "   AI Explainer: http://152.42.199.50/ai-explainer.html"
echo "   AI Explainer (BTC): http://152.42.199.50/ai-explainer.html?coin=BTC"
echo "   AI Explainer (ETH): http://152.42.199.50/ai-explainer.html?coin=ETH"
echo ""
echo "💡 Hard Refresh: Cmd+Shift+R (Mac) or Ctrl+Shift+R (Windows)"
echo ""
