#!/bin/bash

echo "🧪 Testing Import Wallet - Auto Connect Fix"
echo "=============================================="
echo ""
echo "✅ Deployed to: http://152.42.199.50"
echo "📅 Test Date: $(date '+%Y-%m-%d %H:%M:%S')"
echo ""
echo "🔧 Fix Applied:"
echo "   - Added localStorage verification after import"
echo "   - Increased delay before reload (500ms + 1000ms)"
echo "   - Added console logs for debugging"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Test Steps:"
echo ""
echo "1. Preparation"
echo "   - Open http://152.42.199.50"
echo "   - Hard refresh: Cmd+Shift+R (Mac) or Ctrl+Shift+R (Windows)"
echo "   - Open browser console (F12) to see logs"
echo ""
echo "2. Create & Export Wallet (if you don't have backup)"
echo "   - Click 'Connect Wallet'"
echo "   - Click 'Create New Wallet'"
echo "   - Wait for wallet creation"
echo "   - Backup mnemonic"
echo "   - Click wallet button → '📦 Export Wallet'"
echo "   - Enter password: 'testpass123'"
echo "   - Confirm password: 'testpass123'"
echo "   - Click 'Export Wallet'"
echo "   - ✅ Backup file downloads"
echo ""
echo "3. Disconnect Wallet"
echo "   - Click wallet button"
echo "   - Click 'Disconnect'"
echo "   - ✅ Wallet should disconnect"
echo "   - ✅ Button should show 'Connect Wallet'"
echo ""
echo "4. Import Wallet"
echo "   - Click 'Connect Wallet'"
echo "   - Click '📥 Import Existing Wallet'"
echo "   - Select your backup .json file"
echo "   - Enter password: 'testpass123'"
echo "   - Click 'Import Wallet'"
echo ""
echo "5. Verify Auto-Connect ⭐ CRITICAL"
echo "   - ✅ Should show 'Wallet imported successfully! Reloading...'"
echo "   - ✅ Console should show:"
echo "      - '✅ Wallet imported: {...}'"
echo "      - '🔍 Verifying saved data:'"
echo "      - '   Mnemonic: Found'"
echo "      - '   Chain ID: <your_chain_id>'"
echo "      - '   Owner: <your_owner>'"
echo "   - ✅ Page should reload after ~1.5 seconds"
echo "   - ✅ After reload, console should show:"
echo "      - '🚀 AI POWER TRADE - Initializing...'"
echo "      - '📦 Found saved wallet data:'"
echo "      - '   Chain ID: <your_chain_id>'"
echo "      - '   Owner: <your_owner>'"
echo "      - '✅ Wallet restored successfully'"
echo "   - ✅ Wallet button should show chain ID (not 'Connect Wallet')"
echo "   - ✅ Status should show '✅ Ready to trade!'"
echo "   - ✅ Portfolio should show balance"
echo "   - ✅ Faucet should be ready"
echo ""
echo "6. Verify Wallet Info"
echo "   - Click wallet button"
echo "   - ✅ Should show 'Wallet Connected'"
echo "   - ✅ Chain ID should match original"
echo "   - ✅ Owner should match original"
echo "   - ✅ Status should be 'Connected'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🐛 Debugging Tips:"
echo ""
echo "If wallet doesn't auto-connect after import:"
echo ""
echo "1. Check Console Logs"
echo "   - Look for '🔍 Verifying saved data:'"
echo "   - Check if Mnemonic, Chain ID, Owner are all present"
echo "   - Look for any error messages"
echo ""
echo "2. Check localStorage"
echo "   - Open Console (F12)"
echo "   - Type: localStorage.getItem('linera_mnemonic')"
echo "   - Type: localStorage.getItem('linera_chain_id')"
echo "   - Type: localStorage.getItem('linera_owner')"
echo "   - All should return values (not null)"
echo ""
echo "3. Manual Reload"
echo "   - If auto-reload doesn't work"
echo "   - Manually refresh page (F5)"
echo "   - Wallet should connect on manual reload"
echo ""
echo "4. Clear Cache"
echo "   - If still not working"
echo "   - Hard refresh: Cmd+Shift+R"
echo "   - Or open in incognito mode"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Expected Result:"
echo "   After import and reload, wallet should be AUTOMATICALLY CONNECTED"
echo "   with all data restored (Chain ID, Owner, Balance)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
