#!/bin/bash

echo "🔍 Detailed Risk Management Test"
echo "=================================="
echo ""
echo "🌐 URL: http://152.42.199.50"
echo ""
echo "📋 DETAILED TEST STEPS:"
echo ""
echo "1️⃣ CONNECT WALLET"
echo "   - Click 'Connect Wallet' button"
echo "   - Wait for wallet creation"
echo "   - Verify wallet connected"
echo ""
echo "2️⃣ CLAIM FAUCET (if balance is 0)"
echo "   - Click 'Claim Test Tokens'"
echo "   - Wait for success message"
echo "   - Verify balance updated"
echo ""
echo "3️⃣ SELECT COIN"
echo "   - Click 'BTC' button"
echo "   - Verify BTC is highlighted"
echo ""
echo "4️⃣ GENERATE SIGNAL"
echo "   - Click 'Generate Signal' button"
echo "   - Wait for AI analysis"
echo "   - Check console for logs:"
echo "     * '🧠 Signal generated with REAL ANALYSIS'"
echo "     * '📊 RSI: ...'"
echo "     * '🎯 Risk Management: ...'"
echo ""
echo "5️⃣ CHECK RISK MANAGEMENT SECTION"
echo "   - Verify section is visible"
echo "   - Check fields are populated:"
echo "     * Take Profit Price: (should have value)"
echo "     * Take Profit %: (should have value)"
echo "     * Stop Loss Price: (should have value)"
echo "     * Stop Loss %: (should have value)"
echo "     * Risk/Reward Ratio: (e.g., 'R:R 1.67:1')"
echo "     * TP Profit: (e.g., '+$123.45')"
echo "     * SL Loss: (e.g., '-$67.89')"
echo ""
echo "6️⃣ TEST AI SUGGEST TP BUTTON"
echo "   - Click '🎯 AI Suggest' button (Take Profit)"
echo "   - Check console for:"
echo "     * '🎯 AI TP Suggestion - Signal data: { price: ..., confidence: ..., type: ... }'"
echo "     * '✅ AI TP Suggestion: { takeProfit: ..., takeProfitPercent: ... }'"
echo "   - Verify TP fields updated"
echo ""
echo "7️⃣ TEST AI SUGGEST SL BUTTON"
echo "   - Click '🎯 AI Suggest' button (Stop Loss)"
echo "   - Check console for:"
echo "     * '🎯 AI SL Suggestion - Signal data: { price: ..., confidence: ..., type: ... }'"
echo "     * '✅ AI SL Suggestion: { stopLoss: ..., stopLossPercent: ... }'"
echo "   - Verify SL fields updated"
echo ""
echo "8️⃣ TEST MANUAL INPUT - TP PERCENTAGE"
echo "   - Change 'Take Profit %' to '10'"
echo "   - Verify 'Take Profit Price' updates automatically"
echo "   - Verify 'TP Profit' updates"
echo ""
echo "9️⃣ TEST MANUAL INPUT - SL PRICE"
echo "   - Change 'Stop Loss Price' manually"
echo "   - Verify 'Stop Loss %' updates automatically"
echo "   - Verify 'SL Loss' updates"
echo ""
echo "🔟 TEST TRADE AMOUNT SLIDER"
echo "   - Move slider to 50%"
echo "   - Verify 'Trade Amount' updates"
echo "   - Verify 'TP Profit' and 'SL Loss' recalculate"
echo ""
echo "❌ COMMON ERRORS TO CHECK:"
echo "   - 'Cannot read properties of undefined (reading price)'"
echo "   - 'Cannot read properties of undefined (reading type)'"
echo "   - 'Cannot read percentage'"
echo "   - TP/SL fields showing 'NaN' or empty"
echo "   - Profit/Loss showing '$NaN' or '$0.00' when should have value"
echo ""
echo "✅ SUCCESS CRITERIA:"
echo "   - All fields populate automatically after signal generation"
echo "   - AI Suggest buttons work without errors"
echo "   - Manual input updates work (price ↔ percentage sync)"
echo "   - Profit/Loss calculations display correctly"
echo "   - No console errors"
echo ""
echo "🐛 DEBUG TIPS:"
echo "   - Open Browser Console (F12 or Cmd+Option+I)"
echo "   - Look for console.log messages starting with:"
echo "     * 🧠 (signal generation)"
echo "     * 🎯 (AI suggestions)"
echo "     * 💰 (risk calculations)"
echo "   - Check for red error messages"
echo ""
echo "🌐 Opening browser in 3 seconds..."
sleep 3
open "http://152.42.199.50"
