#!/bin/bash

echo "⏱️ Testing 15-Minute Signal Cooldown (Prototype)..."
echo ""
echo "✅ Features Implemented:"
echo "   - 15-minute cooldown per coin"
echo "   - Countdown timer on button"
echo "   - Alert message with remaining time"
echo "   - Signal saved to localStorage"
echo "   - Button disabled during cooldown"
echo ""
echo "🔍 How to Test:"
echo ""
echo "1️⃣  Open Dashboard (incognito mode):"
echo "   http://152.42.199.50/"
echo ""
echo "2️⃣  Create wallet & select BTC"
echo ""
echo "3️⃣  Click 'Generate Signal' (first time):"
echo "   ✅ Should work normally"
echo "   ✅ Signal generated"
echo "   ✅ Button changes to: 'Next signal in: 14m 59s'"
echo ""
echo "4️⃣  Try clicking button again:"
echo "   ✅ Button is disabled"
echo "   ✅ Shows countdown timer"
echo ""
echo "5️⃣  Try clicking anyway (if enabled):"
echo "   ✅ Alert: 'Please wait Xm Ys before generating...'"
echo ""
echo "6️⃣  Switch to ETH:"
echo "   ✅ Button enabled (different coin)"
echo "   ✅ Can generate ETH signal"
echo "   ✅ ETH now has its own 15-min cooldown"
echo ""
echo "7️⃣  Switch back to BTC:"
echo "   ✅ Still shows countdown"
echo "   ✅ Cooldown persists per coin"
echo ""
echo "8️⃣  Wait 15 minutes (or clear localStorage):"
echo "   ✅ Button enabled again"
echo "   ✅ Can generate new signal"
echo ""
echo "🧪 Testing Tips:"
echo "   • Open Console (F12) to see logs"
echo "   • Check localStorage: signalCooldowns"
echo "   • To skip wait: localStorage.removeItem('signalCooldowns')"
echo "   • Countdown updates every second"
echo ""
echo "🎯 Expected Behavior:"
echo "   ✅ First signal: Works immediately"
echo "   ✅ Second signal (same coin): Blocked for 15 mins"
echo "   ✅ Different coin: Works immediately"
echo "   ✅ Button shows countdown: '14m 32s'"
echo "   ✅ After 15 mins: Button enabled again"
echo ""
echo "📍 Test URL: http://152.42.199.50/"
echo ""
echo "💡 Use incognito mode or hard refresh (Cmd+Shift+R)!"
