#!/bin/bash

echo "🧪 Testing Trade Confirmation Modal Feature"
echo "=========================================="
echo ""
echo "✅ Deployed to: http://152.42.199.50"
echo ""
echo "📋 Test Steps:"
echo "1. Open http://152.42.199.50 in browser (use incognito or hard refresh)"
echo "2. Connect wallet (or create new wallet)"
echo "3. Select a coin (BTC, ETH, SOL, or BNB)"
echo "4. Click 'Generate AI Signal' button"
echo "5. Wait for signal to generate"
echo "6. Click 'Execute AI Trade' button"
echo "7. ✅ EXPECTED: Confirmation modal should appear with:"
echo "   - Signal type (BUY/SELL/HOLD) and coin"
echo "   - Trade amount in USDT and percentage"
echo "   - Price, Confidence, Risk Score"
echo "   - Stop Loss and Take Profit values"
echo "   - Warning message about irreversible transaction"
echo "   - Cancel and 'Confirm & Execute Trade' buttons"
echo "8. Click 'Cancel' - modal should close, trade NOT executed"
echo "9. Click 'Execute AI Trade' again"
echo "10. Click 'Confirm & Execute Trade' - modal closes, trade executes"
echo "11. ✅ EXPECTED: Trade appears in history, signal cleared"
echo ""
echo "🔍 Check browser console for:"
echo "   - '📋 Trade confirmation modal shown' when modal opens"
echo "   - '❌ Trade confirmation cancelled' when clicking Cancel"
echo "   - '⚡ Trade executed:' when confirming"
echo ""
echo "🌐 Opening browser..."
open http://152.42.199.50 2>/dev/null || xdg-open http://152.42.199.50 2>/dev/null || echo "Please open http://152.42.199.50 manually"
