#!/bin/bash

echo "🔄 Testing AI Explainer Sync with Dashboard Signal..."
echo ""
echo "✅ Changes deployed:"
echo "   - AI Explainer now reads coin from URL parameter (?coin=BTC)"
echo "   - Dashboard updates AI Explainer link when coin is selected"
echo "   - Both use same AIExplainer engine for consistent analysis"
echo ""
echo "🔍 How to Test Sync:"
echo ""
echo "1️⃣  Open Dashboard:"
echo "   http://152.42.199.50/"
echo ""
echo "2️⃣  Select a coin (e.g., ETH):"
echo "   - Click on ETH button"
echo "   - Notice AI Explainer link updates"
echo ""
echo "3️⃣  Generate Signal:"
echo "   - Click 'Generate Signal'"
echo "   - Note the signal: BUY/SELL/HOLD"
echo "   - Note confidence: e.g., 75.3%"
echo "   - Note risk score: e.g., 45/100"
echo ""
echo "4️⃣  Open AI Explainer:"
echo "   - Click '🧠 AI Explainer' button"
echo "   - Should open: http://152.42.199.50/ai-explainer.html?coin=ETH"
echo "   - ETH should be selected automatically"
echo ""
echo "5️⃣  Verify Sync:"
echo "   - Signal should match (BUY/SELL/HOLD)"
echo "   - Confidence should be similar (±2% due to timing)"
echo "   - Risk score should be similar (±5 points)"
echo "   - RSI, MACD, MA, BB values should match"
echo ""
echo "💡 Why might values differ slightly?"
echo "   - Market data updates every 30 seconds"
echo "   - Price history is generated with slight randomness"
echo "   - But overall signal direction should be consistent"
echo ""
echo "🎯 Expected Behavior:"
echo "   ✅ Same coin selected in both pages"
echo "   ✅ Same signal direction (BUY/SELL/HOLD)"
echo "   ✅ Similar confidence and risk scores"
echo "   ✅ Same technical indicator values"
echo ""
echo "📍 Test URLs:"
echo "   Dashboard: http://152.42.199.50/"
echo "   AI Explainer (BTC): http://152.42.199.50/ai-explainer.html?coin=BTC"
echo "   AI Explainer (ETH): http://152.42.199.50/ai-explainer.html?coin=ETH"
echo "   AI Explainer (SOL): http://152.42.199.50/ai-explainer.html?coin=SOL"
echo "   AI Explainer (BNB): http://152.42.199.50/ai-explainer.html?coin=BNB"
